#Editted
parameters:
    env(OAUTH2_RSAKEY_PUBLIC): '%kernel.project_dir%/public.key'
    env(OAUTH2_RSAKEY_PRIVATE): '%kernel.project_dir%/private.key'
    env(OAUTH2_RSAKEY_PRIVATE_PASS): ''

trikoder_oauth2:

    authorization_server:
        private_key: '%env(OAUTH2_RSAKEY_PRIVATE)%'
        # Passphrase of the private key                      
        private_key_passphrase: '%env(OAUTH2_RSAKEY_PRIVATE_PASS)%'                           

        encryption_key: '%env(string:OAUTH2_ENCRYPTION_KEY)%'   # (Optional) Change this

    resource_server:
        public_key: '%env(OAUTH2_RSAKEY_PUBLIC)%'                   

    # Scopes that you wish to utilize in your application.
    # This should be a simple array of strings.
    scopes:               ['profile','email','openid','admin']

    # Configures different persistence methods that can be used by the bundle for saving client and token data.
    # Only one persistence method can be configured at a time.
    persistence:          # Required
        #in_memory:            ~
        doctrine:
            # Name of the entity manager that you wish to use for managing clients and tokens.
            entity_manager:       default
